// ----------------------------------------------------------------------------------------------------------------
/*
    Author      : Zidmann (emmanuel.zidel@gmail.com)
    Script      : number.qvs
    Version     : 0.0.0
    Description : Module containing all the useful number functions
 */
// ----------------------------------------------------------------------------------------------------------------

LET vErrorCount = $(ScriptErrorCount);

// ----------------------------------------------------------------------------------------------------------------
// FUNCTIONS TO INTERACT WITH THE NUMBERS
// ----------------------------------------------------------------------------------------------------------------

/*
 * Description : Return 0 if the number is positive or its value
 *       Input : $1 - Number to process
 *      Output : None
 */
SET number_pos = IF($1>0, +$1, 0);

/*
 * Description : Return 0 if the number is negative or its value
 *       Input : $1 - Number to process
 *      Output : None
 */
SET number_neg = IF($1<0, -$1, 0);

/*
 * Description : Return which sign has a number (0 is considered having no sign)
 *       Input : $1 - Number to process
 *      Output : None
 */
SET number_sign = IF($1=0, '0', IF($1>0, '+', '-'));

/*
 * Description : Return the absolute value of a number
 *       Input : $1 - Number to process
 *      Output : None
 */
SET number_abs = FABS($1);

/*
 * Description : Return the order in the 10 base of a number
 *       Input : $1 - Number to process
 *      Output : None
 */
SET number_order = IF(FABS($1)>=10, FLOOR(LOG10(FABS($1))),0);

// ----------------------------------------------------------------------------------------------------------------
// PRINT IF THE LOADING FINISHED WITH OR WITHOUT ANY ERRORS
// ----------------------------------------------------------------------------------------------------------------
LET vDiffErrorCount = $(ScriptErrorCount) - vErrorCount;
IF (vDiffErrorCount > 0) THEN
    call console_error('Date module loaded with $(vDiffErrorCount) error(s)');
ELSE
    call console_info('Date module successfully loaded');
END IF;
